### ISSUE TITLE
Help Wanted: Difficulty Option Auto-tracking

### ISSUE THREAD

**Issue by Fairweather-Furry** [JackTHerbert/wl4_jth#5]
As of right now, users must manually set their difficulty in the tracker. Figuring what in the rom file determines difficulty would be a big help in allowing the tracker to swap itself automatically.

**Comment by lilDavid** [comment]
Current difficulty level is stored at IWRAM address 0x0017 (or system bus address 0x3000017), with value 0 for Normal, 1 for Hard, and 2 for S-Hard.

Rando forces the difficulty level with the instruction at ROM address 0x091558 (or system bus address 0x8091558). Because of the way THUMB instructions are encoded, you can actually read the byte at that address to get the seed's difficulty.
